export const UPDATE_BUILD_COUNT = 'UPDATE_BUILD_COUNT';
export const UPDATE_APP_COUNT = 'UPDATE_APP_COUNT';
export const ADD_NEW_APP = 'ADD_NEW_APP';
export const UPDATE_EXISTING_APP = 'DELETE_EXISTING_APP';